version: '3.8'
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=undigitalpassword
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: